apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      envFrom:
        - configMapRef:
            name: audiobookshelf-configmap
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.22.0
          ports:
            - containerPort: 3005
