apiVersion: kustomize.config.k8s.io/v1beta1Add commentMore actions
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - linkding-container-env-secret.yaml