apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/controllers/staging
  prune: true
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
  timeout: 5m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-configs 
#  namespace: flux-system
#spec:
#  interval: 1m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./monitoring/configs/staging
#  prune: true
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
#  timeout: 5m
