apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobalt
  template:
    metadata:
      labels:
        app: cobalt
    spec:
      securityContext:
        fsGroup: 33 
        runAsUser: 33
        runAsGroup: 33

      envFrom:
        - configMapRef:
            name: cobalt-config

      containers:
        - name: cobalt
          image: ghcr.io/imputnet/cobalt:11
          ports:
            - containerPort: 9000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

