apiVersion: v1
kind: Service
metadata:
  name: cobalt-frontend-svc
  namespace: cobalt
spec:
  selector:
    app: cobalt-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP