apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:80C7s+gdViFTtutUYxSkVjz/zw6Ng7zGmhqbDUF4Hk0EcG60JGa6WgfHXLTh0uAEP0NWalpHh1vCf1XPiPwhRAGqT70EbDeHBX4BHP5YhU5vMvtZ63Z+SaiLJAqskqJYxd3MDR4wmiRVusOu4aqqI/EWZyHwIk9BKsk74UF1bdGZmVGUmL6eS/DxrN41L/31vQ4b9wdl53/8Bu03K64j2lpivFo4SCXskiV1A7mcC2BDbCLxR0NbXWdqauYTlriUFSj2A9onRcaQegKjqVNth8dzPjBUUlpho9yX2w7hJBakERNHvDaZPHgewSU=,iv:vFXa6V2ZImgZcv85MQ+Vxkw2SFc1VDd4XEAYRSmE7LM=,tag:OKEvttq0qwAiiU3mvb/CxA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mc-control-tunnel-credentials
sops:
    age:
        - recipient: age1wkq48d0dagzfk5qu0utmvrhqnp8ps5flxa5s7cr2vnu3xe4kjftqvef2ce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYUNGN1JhTHBKdGdtR01H
            RmJDRmp0WG91d21nSDhDUXIxeURVREVBNGdrCnNObVNPQ2hkR1VxdVY1U1dyTitO
            dWxrMmloWGM0WjRuU0tvU3Z4M2NNQ0UKLS0tIGttVkRPZXo0eUpQQjFROWQ2L08r
            cldQaUg0RnVHbVNMNEVkeDErK1hRKzgKk473nTwBFlhQ79LCamKLpSf96311m5zM
            pLBma28CD3XqoqkICrY1a8MIXeXe3yo9Y8HpQtpFsRIDo55OHPVSBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T14:17:28Z"
    mac: ENC[AES256_GCM,data:iZ2mhKmvNppTj2BR/MChj7n0RG8nHdYNuDYpVHNofJF4AD0sS8yC74gDN0+WnxxFs4w29bBGdF2jwbK2K1FGErbtWTPx8Voc1R2YNdTHvo8AnRPgzPezpIQ6QSIvIRjkYAsso6YK4JUt7Z9uvBMT5L2yv4E/zEmfKA7fe79dvds=,iv:ZJdUfrD44Zmng0y5JHKGrD37GLUYVC8k5sHIjZLigBk=,tag:6BHQ5dGyJ/cECBowDyByZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
