apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-curator-cron
  namespace: kubejobhunt
spec:
  schedule: "0 4 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ai-curator
            image: siragled/kubejobhunt-ai-curator:latest 
            command: ["/bin/sh", "-c"]
            args:
            - |
              export DATABASE_URL=$(printf "$DATABASE_URL_TEMPLATE" "$POSTGRES_PASSWORD")
              echo "Starting AI curator script..."
              python /app/curator.py
            env:
            - name: DATABASE_URL_TEMPLATE
              valueFrom:
                configMapKeyRef: { name: kubejobhunt-config, key: DATABASE_URL_TEMPLATE }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: kubejobhunt-secrets, key: POSTGRES_PASSWORD }
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef: { name: kubejobhunt-secrets, key: OPENROUTER_API_KEY }
          restartPolicy: OnFailure