apiVersion: v1
kind: Service
metadata:
  name: postgres-db # The name other pods will use to connect
  namespace: kubejobhunt
spec:
  selector:
    app: postgres-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432