apiVersion: batch/v1
kind: CronJob
metadata:
  name: processor-cron
  namespace: kubejobhunt
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: processor
            image: siragled/kubejobhunt-processor:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              export DATABASE_URL=$(printf "$DATABASE_URL_TEMPLATE" "$POSTGRES_PASSWORD")
              echo "Processor starting..."
              python /app/processor.py
            env:
            - name: JOBSPY_API_URL
              valueFrom:
                configMapKeyRef: { name: kubejobhunt-config, key: JOBSPY_API_URL }
            - name: DATABASE_URL_TEMPLATE 
              valueFrom:
                configMapKeyRef: { name: kubejobhunt-config, key: DATABASE_URL_TEMPLATE }
            - name: POSTGRES_PASSWORD 
              valueFrom:
                secretKeyRef: { name: kubejobhunt-secrets, key: POSTGRES_PASSWORD }
            - name: JOBSPY_API_KEY
              valueFrom:
                secretKeyRef: { name: kubejobhunt-secrets, key: API_KEY }
          restartPolicy: OnFailure