apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: kubejobhunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: siragled/kubejobhunt-web-ui:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
        - |
          export DATABASE_URL=$(printf "$DATABASE_URL_TEMPLATE" "$POSTGRES_PASSWORD")
          uvicorn main:app --host 0.0.0.0 --port 80
        env:
        - name: DATABASE_URL_TEMPLATE
          valueFrom:
            configMapKeyRef:
              name: kubejobhunt-config
              key: DATABASE_URL_TEMPLATE
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: kubejobhunt-secrets
              key: POSTGRES_PASSWORD