apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: influx
spec:
  selector:
    app: samba
  ports:
  - name: smb-port
    port: 445
    targetPort: 445
  - name: netbios-ssn
    port: 139
    targetPort: 139
  type: NodePort