apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        ports:
        - containerPort: 9091  
        volumeMounts:
        - name: downloads
          mountPath: /downloads
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Amsterdam"
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: media-pvc