apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        ports:
        - containerPort: 9091  
        volumeMounts:
        - name: downloads
          mountPath: /downloads
        env:
        - name: WEBUI_PORT
          valueFrom:
            configMapKeyRef:
              name: qbittorrent-config
              key: WEBUI_PORT
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: qbittorrent-config
              key: TZ
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: qbittorrent-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: qbittorrent-config
              key: PGID
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: media-pvc