apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-control
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-control
  template:
    metadata:
      labels:
        app: mc-control
    spec:
      serviceAccountName: mc-control
      containers:
      - name: control
        image: siragled/mc-control:latest
        ports:
        - containerPort: 8080
        env:
        - name: DEPLOYMENT
          value: minecraft
        - name: NAMESPACE
          value: minecraft