apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - storage.yaml
  - service.yaml
  - rbac.yaml
  - control-dep.yaml
  - control-svc.yaml
  # - monitor-config.yaml
  # - monitor.yaml