apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - minecraft-deployment.yaml
  - minecraft-monitor.yaml
  - storage.yaml
  - minecraft-service.yaml
  - prometheus-rule.yaml
  - scaler-webhook.yaml