apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-idle-monitor
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-idle-monitor
  template:
    metadata:
      labels:
        app: mc-idle-monitor
    spec:
      containers:
      - name: monitor
        image: siragled/mc-monitor-custom:latest
        command: ["/bin/bash", "/script/monitor.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /script
        - name: kubeconfig
          mountPath: /kube
          readOnly: true
        env:
        - name: KUBECONFIG
          value: /kube/config
      volumes:
      - name: mc-idle-script
        configMap:
          name: mc-idle-script
          defaultMode: 0755
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
