apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-idle-monitor
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-idle-monitor
  template:
    metadata:
      labels:
        app: mc-idle-monitor
    spec:
      containers:
      - name: monitor
        image: itzg/mc-monitor
        command: ["/bin/sh", "/script/monitor.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /script
        - name: kubeconfig
          mountPath: /root/.kube
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: script-volume
        configMap:
          name: mc-idle-script
          defaultMode: 0755
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
