apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-idle-script
  namespace: games
data:
  monitor.sh: |
    #!/bin/bash

    DEPLOYMENT="mc-server"
    NAMESPACE="games"
    IDLE_MINUTES=15
    CHECK_INTERVAL=60
    IDLE_COUNT=0

    echo "[monitor] Watching Minecraft server activity..."

    while true; do
      # Query player count using mc-monitor
      player_count=$(mc-monitor status --host localhost --port 25565 | grep -oP '(?<=players: )\d+')

      echo "[monitor] Player count: $player_count"

      if [[ "$player_count" == "0" || -z "$player_count" ]]; then
        IDLE_COUNT=$((IDLE_COUNT + 1))
      else
        IDLE_COUNT=0
      fi

      total_idle_minutes=$((IDLE_COUNT * CHECK_INTERVAL / 60))

      echo "[monitor] Idle minutes: $total_idle_minutes / $IDLE_MINUTES"

      if (( total_idle_minutes >= IDLE_MINUTES )); then
        echo "[monitor] No activity for $IDLE_MINUTES minutes. Scaling down $DEPLOYMENT..."
        kubectl scale deployment "$DEPLOYMENT" -n "$NAMESPACE" --replicas=0
        exit 0
      fi

      sleep $CHECK_INTERVAL
    done
