apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-monitor
  namespace: minecraft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-mc
  namespace: minecraft
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mc-monitor-bind
  namespace: minecraft
subjects:
- kind: ServiceAccount
  name: mc-monitor
roleRef:
  kind: Role
  name: scale-mc
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-control
  namespace: minecraft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: minecraft
  name: mc-control-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mc-control-binding
  namespace: minecraft
subjects:
- kind: ServiceAccount
  name: mc-control
roleRef:
  kind: Role
  name: mc-control-role
  apiGroup: rbac.authorization.k8s.io
